// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkqpdqxevazonedxwmru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrcXBkcXhldmF6b25lZHh3bXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDYzNTUsImV4cCI6MjA2NzYyMjM1NX0.VtKOpps3r0gP-xH9TH0-bi5tjDmTa5ZN6mSX2VtVufo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});